spring.datasource.url: jdbc:mysql://localhost:3306/devblog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: SkillBox-loxi1114
spring.jpa.hibernate.ddl-auto: update
blog.title : DevHub
blog.subtitle : Developer stories
blog.phone : +7 911 234 56 78
blog.email : sobaka@so.baka
blog.copyright : copyright
blog.copyrightFrom : copyrightFrom