spring.datasource.url: jdbc:mysql://localhost:3306/devblog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: securepassword
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql : false
spring.mail.host : smtp.gmail.com
spring.mail.port : 587
spring.mail.username : <login user to smtp server>
spring.mail.password : <login password to smtp server>
spring.mail.properties.mail.smtp.auth : true
spring.mail.properties.mail.smtp.starttls.enable : true
blog.title : DevHub
blog.subtitle : Developer stories
blog.phone : +7 911 234 56 78
blog.email : sobaka@so.baka
blog.copyright : copyright
blog.copyrightFrom : copyrightFrom