spring.datasource.url: jdbc:mysql://localhost:3306/devblog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: SkillBox-loxi1114
spring.jpa.hibernate.ddl-auto: update